# Generated by Django 5.1 on 2024-09-07 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_alter_todoitem_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='key',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='key',
        ),
    ]
