# Generated by Django 5.1 on 2024-09-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_remove_contact_key_remove_todoitem_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
