# Generated by Django 5.1 on 2024-09-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='inWichSection',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
