# Generated by Django 5.1 on 2024-09-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_contact_inicialcolor_contact_inicials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='subtasks',
            field=models.JSONField(default=list),
        ),
    ]
