# Generated by Django 5.1 on 2024-09-12 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0007_alter_todoitem_subtasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, to='todos.contact'),
        ),
    ]
