# Generated by Django 5.1 on 2024-09-17 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0010_alter_usertoken_token_alter_usertoken_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
